/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedActivityLogsRouteImport } from './routes/_authenticated/activity-logs'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated/locations'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedMutationsRouteImport } from './routes/_authenticated/mutations'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedQrRouteImport } from './routes/_authenticated/qr'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedWorkTypesRouteImport } from './routes/_authenticated/work-types'
import { Route as ScanTokenRouteImport } from './routes/scan.$token'
import { Route as AuthenticatedAssetsIdRouteImport } from './routes/_authenticated/assets_.$id'
import { Route as AuthenticatedTransactionsInRouteImport } from './routes/_authenticated/transactions/in'
import { Route as AuthenticatedTransactionsOutRouteImport } from './routes/_authenticated/transactions/out'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityLogsRoute =
  AuthenticatedActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMutationsRoute = AuthenticatedMutationsRouteImport.update({
  id: '/mutations',
  path: '/mutations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrRoute = AuthenticatedQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkTypesRoute = AuthenticatedWorkTypesRouteImport.update({
  id: '/work-types',
  path: '/work-types',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ScanTokenRoute = ScanTokenRouteImport.update({
  id: '/scan/$token',
  path: '/scan/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssetsIdRoute = AuthenticatedAssetsIdRouteImport.update({
  id: '/assets_/$id',
  path: '/assets/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsInRoute =
  AuthenticatedTransactionsInRouteImport.update({
    id: '/transactions/in',
    path: '/transactions/in',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTransactionsOutRoute =
  AuthenticatedTransactionsOutRouteImport.update({
    id: '/transactions/out',
    path: '/transactions/out',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/mutations': typeof AuthenticatedMutationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/qr': typeof AuthenticatedQrRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/work-types': typeof AuthenticatedWorkTypesRoute
  '/scan/$token': typeof ScanTokenRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/transactions/in': typeof AuthenticatedTransactionsInRoute
  '/transactions/out': typeof AuthenticatedTransactionsOutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/mutations': typeof AuthenticatedMutationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/qr': typeof AuthenticatedQrRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/work-types': typeof AuthenticatedWorkTypesRoute
  '/scan/$token': typeof ScanTokenRoute
  '/assets/$id': typeof AuthenticatedAssetsIdRoute
  '/transactions/in': typeof AuthenticatedTransactionsInRoute
  '/transactions/out': typeof AuthenticatedTransactionsOutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/mutations': typeof AuthenticatedMutationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/qr': typeof AuthenticatedQrRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/work-types': typeof AuthenticatedWorkTypesRoute
  '/scan/$token': typeof ScanTokenRoute
  '/_authenticated/assets_/$id': typeof AuthenticatedAssetsIdRoute
  '/_authenticated/transactions/in': typeof AuthenticatedTransactionsInRoute
  '/_authenticated/transactions/out': typeof AuthenticatedTransactionsOutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity-logs'
    | '/assets'
    | '/audit'
    | '/categories'
    | '/dashboard'
    | '/loans'
    | '/locations'
    | '/maintenance'
    | '/mutations'
    | '/profile'
    | '/qr'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/users'
    | '/vendors'
    | '/work-types'
    | '/scan/$token'
    | '/assets/$id'
    | '/transactions/in'
    | '/transactions/out'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity-logs'
    | '/assets'
    | '/audit'
    | '/categories'
    | '/dashboard'
    | '/loans'
    | '/locations'
    | '/maintenance'
    | '/mutations'
    | '/profile'
    | '/qr'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/users'
    | '/vendors'
    | '/work-types'
    | '/scan/$token'
    | '/assets/$id'
    | '/transactions/in'
    | '/transactions/out'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/activity-logs'
    | '/_authenticated/assets'
    | '/_authenticated/audit'
    | '/_authenticated/categories'
    | '/_authenticated/dashboard'
    | '/_authenticated/loans'
    | '/_authenticated/locations'
    | '/_authenticated/maintenance'
    | '/_authenticated/mutations'
    | '/_authenticated/profile'
    | '/_authenticated/qr'
    | '/_authenticated/reports'
    | '/_authenticated/scan'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/vendors'
    | '/_authenticated/work-types'
    | '/scan/$token'
    | '/_authenticated/assets_/$id'
    | '/_authenticated/transactions/in'
    | '/_authenticated/transactions/out'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ScanTokenRoute: typeof ScanTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity-logs': {
      id: '/_authenticated/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AuthenticatedActivityLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mutations': {
      id: '/_authenticated/mutations'
      path: '/mutations'
      fullPath: '/mutations'
      preLoaderRoute: typeof AuthenticatedMutationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr': {
      id: '/_authenticated/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof AuthenticatedQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-types': {
      id: '/_authenticated/work-types'
      path: '/work-types'
      fullPath: '/work-types'
      preLoaderRoute: typeof AuthenticatedWorkTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/scan/$token': {
      id: '/scan/$token'
      path: '/scan/$token'
      fullPath: '/scan/$token'
      preLoaderRoute: typeof ScanTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assets_/$id': {
      id: '/_authenticated/assets_/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/in': {
      id: '/_authenticated/transactions/in'
      path: '/transactions/in'
      fullPath: '/transactions/in'
      preLoaderRoute: typeof AuthenticatedTransactionsInRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/out': {
      id: '/_authenticated/transactions/out'
      path: '/transactions/out'
      fullPath: '/transactions/out'
      preLoaderRoute: typeof AuthenticatedTransactionsOutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityLogsRoute: typeof AuthenticatedActivityLogsRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMutationsRoute: typeof AuthenticatedMutationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQrRoute: typeof AuthenticatedQrRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedWorkTypesRoute: typeof AuthenticatedWorkTypesRoute
  AuthenticatedAssetsIdRoute: typeof AuthenticatedAssetsIdRoute
  AuthenticatedTransactionsInRoute: typeof AuthenticatedTransactionsInRoute
  AuthenticatedTransactionsOutRoute: typeof AuthenticatedTransactionsOutRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityLogsRoute: AuthenticatedActivityLogsRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMutationsRoute: AuthenticatedMutationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQrRoute: AuthenticatedQrRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedWorkTypesRoute: AuthenticatedWorkTypesRoute,
  AuthenticatedAssetsIdRoute: AuthenticatedAssetsIdRoute,
  AuthenticatedTransactionsInRoute: AuthenticatedTransactionsInRoute,
  AuthenticatedTransactionsOutRoute: AuthenticatedTransactionsOutRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ScanTokenRoute: ScanTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
